# Generated by Django 4.2.4 on 2023-09-19 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registeration',
        ),
    ]
