# Generated by Django 4.2.6 on 2023-11-13 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0003_rename_name_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('divorced', models.BooleanField()),
                ('date_checked', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n1', models.FloatField(help_text='When one of you apologizes after a discussion goes in a bad direction, does it extend?')),
                ('n2', models.FloatField(help_text="Do you ignore each other's differences at the end of the day?")),
                ('n3', models.FloatField(help_text='Do you and your partner take discussions to correct your issues?')),
                ('n4', models.FloatField(help_text='Do you and your partner contact each other after an argument?')),
                ('n5', models.FloatField(help_text='Is time spent with your partner special?')),
                ('n6', models.FloatField(help_text='Do you have time for each other at home?')),
                ('n7', models.FloatField(help_text='Are you and your partner like strangers at home?')),
                ('n8', models.FloatField(help_text='Do you enjoy holidays with your partner?')),
                ('n9', models.FloatField(help_text='Do you enjoy travelling with your partner?')),
                ('n10', models.FloatField(help_text='Do you and your partner have similar goals?')),
                ('n11', models.FloatField(help_text='Do you think that you and your partner can live in harmony?')),
                ('n12', models.FloatField(help_text='Do you and your partner have similar values in terms of personal freedom?')),
                ('n13', models.FloatField(help_text='Do you both have similar goals for your children or friends?')),
                ('n14', models.FloatField(help_text='Do you both have similar dreams on how you want to live?')),
                ('n15', models.FloatField(help_text='Do the both of you have similar ideas on what love should be?')),
                ('n16', models.FloatField(help_text='Do you share the same views about being happy in life?')),
                ('n17', models.FloatField(help_text='Do you have similar ideas on what marriage should be?')),
                ('n18', models.FloatField(help_text='Do you have similar ideas about how roles should be in marriage?')),
                ('n19', models.FloatField(help_text='Do the both of you have similar values in trust?')),
                ('n20', models.FloatField(help_text='Do you know what your partner likes?')),
                ('n21', models.FloatField(help_text='Do you know how to take care of your partner when they are sick?')),
                ('n22', models.FloatField(help_text="Do you know your partner's favourite meal?")),
                ('n23', models.FloatField(help_text='Can you tell when your partner is stressed?')),
                ('n24', models.FloatField(help_text="Do you have knowledge of your partner's inner world?")),
                ('n25', models.FloatField(help_text="Do you know your partner's basic concerns?")),
                ('n26', models.FloatField(help_text='Do you know what stresses your partner?')),
                ('n27', models.FloatField(help_text="Do you know your partner's hopes and wishes?")),
                ('n28', models.FloatField(help_text='Do you know your partner very well?')),
                ('n29', models.FloatField(help_text="Do you know your partner's friend circle?")),
                ('n30', models.FloatField(help_text='Do you feel aggressive when you argue with your partner?')),
                ('n31', models.FloatField(help_text='When discussing with your partner do you use vulgar expressions?')),
                ('n32', models.FloatField(help_text="Can you use negative statements about your partner's personality during your discussions?")),
                ('n33', models.FloatField(help_text='Can you use offensive expressions during your discussions?')),
                ('n34', models.FloatField(help_text='Can you insult your partner during your discussions?')),
                ('n35', models.FloatField(help_text='Do you humiliate your partner when you argue?')),
                ('n36', models.FloatField(help_text='Is your argument with your partner calm?')),
                ('n37', models.FloatField(help_text="Do you hate your partner's way of bringing things up?")),
                ('n38', models.FloatField(help_text='Do you and your partner fight during arguments?')),
                ('n39', models.FloatField(help_text="Are you and your partner already fighting before you know what's going on?")),
                ('n40', models.FloatField(help_text='Do you lose your calm when talking to your partner about something?')),
                ('n41', models.FloatField(help_text='When you and your partner are arguing, do you say a word?')),
                ('n42', models.FloatField(help_text='Are you mostly thirsty to calm the environment?')),
                ('n43', models.FloatField(help_text="Do you think it's good for you to leave home for a while?")),
                ('n44', models.FloatField(help_text='Would you rather stay silent than argue with your partner?')),
                ('n45', models.FloatField(help_text='Even if you are right in the argument, are you thirsty to upset the other side?')),
                ('n46', models.FloatField(help_text='When you argue with your partner, do you remain silent because you are afraid of not being able to control your anger?')),
                ('n47', models.FloatField(help_text='Do you feel like you are right during your discussions with your partner?')),
                ('n48', models.FloatField(help_text='Do you have anything to do with what your partner accused you of?')),
                ('n49', models.FloatField(help_text='Are you the one who is wrong about the problems at home?')),
                ('n50', models.FloatField(help_text="Would you hesitate to tell anyone about your partner's inadequacies?")),
                ('n51', models.FloatField(help_text='When you discuss your partner, do you tell people about their inadequacies?')),
                ('n52', models.FloatField(help_text="Lastly, are you afraid of telling people about your partner's inadequacies?")),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
