# Generated by Django 4.2.6 on 2023-11-13 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0004_dps_questions_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Questions',
        ),
        migrations.AlterField(
            model_name='dps',
            name='current_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
