# Generated by Django 4.2.6 on 2023-11-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_delete_questions_alter_dps_current_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dps',
            name='date_checked',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
