# Generated by Django 4.2.6 on 2023-11-13 10:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_dps_date_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dps',
            name='date_checked',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
