# Generated by Django 4.2.6 on 2023-11-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_dps_date_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dps',
            name='divorced',
            field=models.BooleanField(default=False),
        ),
    ]
