# Generated by Django 4.2.6 on 2024-01-31 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0015_alter_divorce_n1_alter_divorce_n10_alter_divorce_n11_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divorce',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
